#
#  MakeFile for "AmigaOS MUI C++ wrapper" project
#
#  Tests
#
#  (c) 2022-2026 TDolphin
#

cross_amigaos_m68k:
	@echo "TODO tests"

morphos_ppc:
	@echo "TODO tests"

cross_morphos_ppc:
	@echo "TODO tests"